### ISSUE TITLE
Improve user console

### ISSUE THREAD

**Issue by MichaelDysart** [MichaelDysart/SYSC4806_Project#55]
Start from https://github.com/MichaelDysart/SYSC4806_Project/tree/%2349_SaveSurveyAnswers

**Comment by MichaelDysart** [comment]
The console is currently just a text area.
I append to the current text area with new messages.

**Comment by MichaelDysart** [comment]
The width is too small for typical message.
It doesn't look like other components.

**Comment by JacksonSchoe** [comment]
Instead, since the TA requested that in the production model not have the console. I'll make it hideable in production through: if (process.env.NODE_ENV !== 'production') {
