### ISSUE TITLE
NumberQuestion logic to determine if an answer is outside the bounds of the min and max?

### ISSUE THREAD

**Issue by JacksonSchoe** [MichaelDysart/SYSC4806_Project#58]

**Comment by MichaelDysart** [comment]
This exists for the server. See lines 124 -126 of
https://github.com/MichaelDysart/SYSC4806_Project/blob/master/src/main/java/webApp/webController.java#L124

It is tested on lines 179 to 185 of
https://github.com/MichaelDysart/SYSC4806_Project/blob/master/src/test/java/webApp/webControllerTest.java#L179,
However, it is only tested for greater than the max, and not tested for less than min. A test should be added for that.

It does not exist for the client, and should be added.

**Comment by JacksonSchoe** [comment]
So leave this issue open then?

**Comment by MichaelDysart** [comment]
Yes
